### ISSUE TITLE
error: could not compile `frame-support`

### ISSUE THREAD

**Issue by duval1024** [substrate-developer-hub/substrate-node-template#49]
I follow the tutorial at [create-your-first-substrate-chain](https://www.substrate.io/tutorials/create-your-first-substrate-chain/v2.0.0-alpha.8)

When I ran `cargo build --release` , some errors happened as follow. My computer was macOs 10.14.3.

```
   Compiling frame-support v2.0.0-alpha.8 (https://github.com/paritytech/substrate.git?tag=v2.0.0-alpha.8#7e9a2ae7)
error[E0424]: expected value, found module `self`
   --> /Users/duval/.cargo/git/checkouts/substrate-7e08433d4c370a21/7e9a2ae/frame/support/src/traits.rs:903:11
    |
901 | / bitmask! {
902 | |     /// Reasons for moving funds out of an account.
903 | |     #[derive(Encode, Decode)]
    | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
904 | |     pub mask WithdrawReasons: i8  where
...   |
919 | |     }
920 | | }
    | |_- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0424`.
error: could not compile `frame-support`.

To learn more, run the command again with --verbose.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by duval1024** [comment]
I found a same closed issue. so I close this issue.

**Comment by duval1024** [comment]
Still I rollback

**Comment by duval1024** [comment]
```
   ~/workspace/blockchain/substrate-node-template   my-first-substrate-chain  rustc --version
rustc 1.45.0-nightly (664fcd3f0 2020-05-27)

```

**Comment by JoshOrndorff** [comment]
It looks like you're still trying to compile with 1.45 which is not currently working. Can you please try to compile with that 1.43 toolchain you have installed?

**Comment by duval1024** [comment]
> It looks like you're still trying to compile with 1.45 which is not currently working. Can you please try to compile with that 1.43 toolchain you have installed?

1.43 toolchain doesn`t work either.

I found a similar issue  [rame-support build fails with latest rust nightly-2020-05-26](https://github.com/paritytech/substrate/issues/6167)

**Comment by duval1024** [comment]
I reinstalled all installed toolchains , and then fixed this problem.
